version: '3'
services:
  mocking:
    build: .
    environment:
      - PORT=8443
      - SLACK_CLIENT_SECRET
      - SLACK_CLIENT_ID
      - PEM_PASS
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      - "/usr/src/app/.data/filedb/"